language: node_js

before_install:
  - curl -sSL https://raw.githubusercontent.com/filiph/install-dart/master/linux/stable.sh | bash

before_script:
  - pub global activate linkcheck

script:
  - linkcheck www.dartlang.org

